// ── aptus-config.js ──────────────────────────────────────────────────────────
// Static configuration: API token, lookup tables, region definitions.
// No runtime dependencies — load this first.
//
// API keys are injected at build time via config.js (generated by build.js).
// See .gitignore — config.js must never be committed.

if (!window.APTUS_CONFIG || !window.APTUS_CONFIG.MAPBOX_TOKEN) {
  throw new Error('[Avenue] window.APTUS_CONFIG.MAPBOX_TOKEN is missing. ' +
    'Ensure config.js is generated by build.js before deploying.');
}

mapboxgl.accessToken = window.APTUS_CONFIG.MAPBOX_TOKEN;

// External Mapbox surfaces that still back the live map experience.
const MAPBOX_STREETS_STYLE = 'mapbox://styles/mapbox/streets-v12';
const MAPBOX_PLACE_LABEL_SOURCE = 'composite';
const MAPBOX_PLACE_LABEL_LAYER = 'place_label';
const MAPBOX_GEOCODING_ENDPOINT = 'https://api.mapbox.com/geocoding/v5/mapbox.places';

const FIPS_TO_STATE = {
  '01': 'Alabama',
  '02': 'Alaska',
  '04': 'Arizona',
  '05': 'Arkansas',
  '06': 'California',
  '08': 'Colorado',
  '09': 'Connecticut',
  '10': 'Delaware',
  '11': 'District of Columbia',
  '12': 'Florida',
  '13': 'Georgia',
  '15': 'Hawaii',
  '16': 'Idaho',
  '17': 'Illinois',
  '18': 'Indiana',
  '19': 'Iowa',
  '20': 'Kansas',
  '21': 'Kentucky',
  '22': 'Louisiana',
  '23': 'Maine',
  '24': 'Maryland',
  '25': 'Massachusetts',
  '26': 'Michigan',
  '27': 'Minnesota',
  '28': 'Mississippi',
  '29': 'Missouri',
  '30': 'Montana',
  '31': 'Nebraska',
  '32': 'Nevada',
  '33': 'New Hampshire',
  '34': 'New Jersey',
  '35': 'New Mexico',
  '36': 'New York',
  '37': 'North Carolina',
  '38': 'North Dakota',
  '39': 'Ohio',
  '40': 'Oklahoma',
  '41': 'Oregon',
  '42': 'Pennsylvania',
  '44': 'Rhode Island',
  '45': 'South Carolina',
  '46': 'South Dakota',
  '47': 'Tennessee',
  '48': 'Texas',
  '49': 'Utah',
  '50': 'Vermont',
  '51': 'Virginia',
  '53': 'Washington',
  '54': 'West Virginia',
  '55': 'Wisconsin',
  '56': 'Wyoming'
};

const REGION_STATES = {
  West:      ['California', 'Oregon', 'Washington', 'Colorado', 'Idaho', 'Montana', 'Nevada', 'Utah', 'Wyoming'],
  Midwest:   ['Illinois', 'Indiana', 'Iowa', 'Kansas', 'Michigan', 'Minnesota', 'Missouri', 'Nebraska', 'North Dakota', 'Ohio', 'South Dakota', 'Wisconsin'],
  Southwest: ['Arizona', 'New Mexico', 'Oklahoma', 'Texas'],
  Southeast: ['Florida', 'Georgia', 'North Carolina', 'South Carolina', 'Virginia', 'West Virginia', 'Alabama', 'Kentucky', 'Mississippi', 'Tennessee', 'Arkansas', 'Louisiana'],
  Northeast: ['Connecticut', 'Maine', 'Massachusetts', 'New Hampshire', 'Rhode Island', 'Vermont', 'New York', 'New Jersey', 'Pennsylvania', 'Delaware', 'Maryland', 'District of Columbia']
};

const REGION_LABEL_POSITIONS = {
  West:      [-114.6, 43.7],
  Midwest:   [-92.0,  43.5],
  Southwest: [-102.2, 32.8],
  Southeast: [-83.5,  35.0],
  Northeast: [-75.8,  41.8]
};

const DEFAULT_VIEW = {
  center: [-98.5795, 39.8283],
  zoom: 4.25
};

const FOCUS_MASK_WORLD_RING = [
  [-179.99,  84.99],
  [ 179.99,  84.99],
  [ 179.99, -84.99],
  [-179.99, -84.99],
  [-179.99,  84.99]
];

// STATE_LABEL_POSITIONS and STATE_SMALL_FONT removed — streets-v12 provides
// state and county labels natively. Only region-level labels are custom.
